/*
 * wf_fit.h - Consumption against speed, as constants.
 *
 * GENERATED by scripts/fit_consumption.py. Do not edit: re-run the
 * tool after adding a Capture and commit what it writes. `make test`
 * fails if this file has drifted from what the archive produces, the
 * same way docs/field-table.md is held to the Field Table.
 *
 * THE FORM. Energy per unit distance is force, so the physically
 * motivated shape is a constant rolling-and-driveline term plus a
 * quadratic drag term:
 *
 *     Wh/km(v) = a + c*v^2      v in km/h
 *
 * This is Consumption - watt-hours per kilometre - and not power,
 * which is force times speed and would go as v^3.
 *
 * WHAT THE FORM LEAVES OUT, and it is the big one. GRADIENT IS NOT
 * MODELLED AND IS THE DOMINANT RESIDUAL. Speed is not the largest
 * input to what a kilometre costs - the road is - and without route
 * knowledge that input is simply missing. Any R^2 below is a
 * statement about the spans that were fitted, never a claim about
 * the next ride. Anything that shows a rider a number derived from
 * these constants is showing them a flat-road estimate, and should
 * say so rather than implying a precision the model does not have.
 *
 * Spans where the Pack was recharged rather than drawn from are kept
 * in the fit, not dropped. Dropping the downhills while the uphills
 * stay would bias every coefficient upward, and a biased fit that
 * looks clean is worse than an honest one with a stated residual.
 *
 * NOTHING FITS ON THE MONITOR. The fit happens offline, over the
 * archive; the Monitor evaluates a polynomial in two constants. See
 * wf_est_consumption_at_speed() in wfest.h, which is the only thing
 * that reads these, and ADR-0005 for why it is built this way.
 *
 * THE FIT BEHIND THESE NUMBERS.
 *   R^2 0.1139 over 299 spans of road, RMS residual 26.770 Wh/km.
 *   Supported from 20.2 to 86.8 km/h. Outside that the evaluator
 *   flags the answer as extrapolated; it is not silently produced.
 *   Captures that contributed: cap0002.
 *   35 of those spans recovered energy rather than spending
 *   it, and were kept - see the note on gradient above.
 *
 * THE ARCHIVE THIS WAS RUN OVER.
 *   cap0002: 130397 records, 2319.0 s, 21284.6 m, 904.572 Wh, peak 85.9 km/h, 419 spans
 *   cap0007: 2668 records, 47.1 s, 21.7 m, 1.629 Wh, peak 7.3 km/h, 2 spans
 *
 * 421 spans closed, 299 accepted.
 *   111 excluded - accelerating: more spread than 20 % of the mean speed, or 3.0 km/h, whichever is larger
 *   2 excluded - incomplete: the Capture ended inside it
 *   9 excluded - stationary: never covered its span of road
 */
#ifndef WF_FIT_H
#define WF_FIT_H

/* 1 when the constants below came out of a fit over real riding, 0
 * when they are the unfitted placeholder. Everything that reads them
 * has to check this first. */
#define WF_FIT_FITTED                1

/* The rolling and driveline term: watt-hours per kilometre at rest,
 * before any drag. */
#define WF_FIT_A_WH_PER_KM           22.451450807572009

/* No linear term was fitted; see the tool's header comment. */
#define WF_FIT_LINEAR                0
#define WF_FIT_B_WH_PER_KM_PER_KMH   0.0

/* The drag term: watt-hours per kilometre per (km/h) squared. */
#define WF_FIT_C_WH_PER_KM_PER_KMH2  0.0053165823038795017

/* The speed range the data actually covers. Asking outside it is
 * extrapolation and is flagged as such - issue #20's suggested speed
 * has to be one of these. Both are zero when there is no fit, so no
 * speed at all is inside the range. */
#define WF_FIT_SPEED_MIN_KMH         20.2027
#define WF_FIT_SPEED_MAX_KMH         86.843900000000005

/* How well it fits, and over how much. Constants so that a Confidence
 * figure on the screen can be built out of the fit rather than out of
 * a comment nobody compiles. */
#define WF_FIT_R2                    0.11391774860932535
#define WF_FIT_SAMPLES               299
#define WF_FIT_RMS_WH_PER_KM         26.769931820820556

/* The Captures that went in, so a coefficient can be traced to the
 * riding it came from. Empty when there is no fit. */
#define WF_FIT_CAPTURES              "cap0002"

#endif /* WF_FIT_H */
