/*
 * wf_fit.h - Consumption against speed, as constants.
 *
 * GENERATED by scripts/fit_consumption.py. Do not edit: re-run the
 * tool after adding a Capture and commit what it writes. `make test`
 * fails if this file has drifted from what the archive produces, the
 * same way docs/field-table.md is held to the Field Table.
 *
 * THE FORM. Energy per unit distance is force, so the physically
 * motivated shape is a constant rolling-and-driveline term plus a
 * quadratic drag term:
 *
 *     Wh/km(v) = a + c*v^2      v in km/h
 *
 * This is Consumption - watt-hours per kilometre - and not power,
 * which is force times speed and would go as v^3.
 *
 * NOTHING FITS ON THE MONITOR. The fit happens offline, over the
 * archive; the Monitor evaluates a polynomial in two constants. See
 * wf_est_consumption_at_speed() in wfest.h, which is the only thing
 * that reads these.
 *
 * THERE IS NO FIT. The coefficients below are placeholders and are
 * marked UNFITTED, in the same spirit as WF_EST_LIMP_POINT_V's
 * provisional marking and the unsettled WF_CTRL_CURRENT_LSB_PER_A.
 * WF_FIT_FITTED is 0, wf_est_consumption_at_speed() produces
 * nothing at any speed, and no figure on the Monitor rests on
 * them.
 *
 *   Why: 0 spans of road survived the exclusions, and 20 is the fewest
 *   worth fitting 2 coefficients to. The archive does not support a
 *   fit.
 *
 *   The steady-speed holds this wants are in the calibration ride,
 *   issue #6, and that ride has not happened.
 *
 * THE ARCHIVE THIS WAS RUN OVER.
 *   cap0007: 2668 records, 47.1 s, 16.7 m, 1.731 Wh, peak 5.6 km/h, 2 spans
 *
 * 2 spans closed, 0 accepted.
 *   1 excluded - incomplete: the Capture ended inside it
 *   1 excluded - stationary: never covered its span of road
 */
#ifndef WF_FIT_H
#define WF_FIT_H

/* 1 when the constants below came out of a fit over real riding, 0
 * when they are the unfitted placeholder. Everything that reads them
 * has to check this first. */
#define WF_FIT_FITTED                0

/* The rolling and driveline term: watt-hours per kilometre at rest,
 * before any drag. */
#define WF_FIT_A_WH_PER_KM           0.0

/* No linear term was fitted; see the tool's header comment. */
#define WF_FIT_LINEAR                0
#define WF_FIT_B_WH_PER_KM_PER_KMH   0.0

/* The drag term: watt-hours per kilometre per (km/h) squared. */
#define WF_FIT_C_WH_PER_KM_PER_KMH2  0.0

/* The speed range the data actually covers. Asking outside it is
 * extrapolation and is flagged as such - issue #20's suggested speed
 * has to be one of these. Both are zero when there is no fit, so no
 * speed at all is inside the range. */
#define WF_FIT_SPEED_MIN_KMH         0.0
#define WF_FIT_SPEED_MAX_KMH         0.0

/* How well it fits, and over how much. Constants so that a Confidence
 * figure on the screen can be built out of the fit rather than out of
 * a comment nobody compiles. */
#define WF_FIT_R2                    0.0
#define WF_FIT_SAMPLES               0
#define WF_FIT_RMS_WH_PER_KM         0.0

/* The Captures that went in, so a coefficient can be traced to the
 * riding it came from. Empty when there is no fit. */
#define WF_FIT_CAPTURES              ""

#endif /* WF_FIT_H */
